const Images = {
  hero: new URL("./header_img.png", import.meta.url).href,
  logo: new URL("./favicon.png", import.meta.url).href,
  card1: new URL("./card1.png", import.meta.url).href,
  card2: new URL("./card2.png", import.meta.url).href,
  card3: new URL("./card3.png", import.meta.url).href,
  card4: new URL("./card4.png", import.meta.url).href,
  about: new URL("./about_img.png", import.meta.url).href,
  check: new URL("./check.png", import.meta.url).href,
  github: new URL("./Github.png", import.meta.url).href,
  microsoft: new URL("./Microsoft.png", import.meta.url).href,
  redis: new URL("./Redis.png", import.meta.url).href,
  amazon: new URL("./Amazon.png", import.meta.url).href,
  paypal: new URL("./Paypal.png", import.meta.url).href,
  linkedin: new URL("./Linkedin.png", import.meta.url).href,
  reddit: new URL("./Reddit.png", import.meta.url).href,
  medium: new URL("./Medium.png", import.meta.url).href,
  alumni1: new URL("./alumni1.png", import.meta.url).href,
  alumni2: new URL("./alumni2.png", import.meta.url).href,
  alumni3: new URL("./alumni3.png", import.meta.url).href,
  alumni4: new URL("./alumni4.png", import.meta.url).href,
  ads: new URL("./Persuasive.png", import.meta.url).href,
};

export default Images;
